### ISSUE TITLE
bug(navigation): on-click of "About" does not route correctly

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#100]
**Environment:**
n/a

**Steps to Recreate:**
- Navigate to openforge.io/contact or /opportunities
- Click "About" link in the navigation

**Expected Result:**
While on Contact or Opportunities pages, on-click of "About" in the nav scrolls to Meet the Team on the home page

**Actual Result:**
While on Contact or Opportunities pages, on-click of "About" in the nav scrolls to User Feedback on the home page

**Comment by nbey** [comment]
It seems like the root cause of this issue is the responsive sizes of images in the **Process** section of the home page. I've looked into scrolling on the `window.load` event, as well as `document.ready`.

I'm not sure what the best solution here is, but it may be possible to calculate the sections' proper position, or we can try ensuring that the images have been loaded first.

 I've been looking into the latter, but have not had any success yet.

**Comment by nbey** [comment]
I've found a potential solution -- if I preload the images in the `#process` section of the page, it properly scrolls the `#about` section into view.
