### ISSUE TITLE
bug-UI(home page - hero): "Let's get Started" button does not function when Services section is hidden

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#101]
**Environment:**
Production 6-11-2018

**Steps to Recreate:**
Navigate to openforge.io on any browser that is smaller than 1400px wide

**Expected Result:**
"Let's Get Started" button scrolls to Services section

**Actual Result:**
"Let's Get Started" button does not function (occurs when Services section is hidden)
_________________________________
**Production:**
![screen shot 2018-05-30 at 2 23 43 pm](https://user-images.githubusercontent.com/37937571/40739865-4beb1762-6415-11e8-8fa4-235b44393edb.png)
![screen shot 2018-05-30 at 2 25 40 pm](https://user-images.githubusercontent.com/37937571/40739901-5beaa01a-6415-11e8-91af-5b7dc7ec08e5.png)

**Comment by PaulPaulDevelops** [comment]
@Wholloran 

So with this issue, it is occurring because the 'services' section is currently hidden when it is in a smaller viewport (pending design updates for smaller viewports).

As a result, it will not scroll to a section that is hidden.

Should we change this temporarily to scroll to our process instead?

**Comment by Wholloran** [comment]
Yeah, I would think that's the best idea. The only other option would be to hide the button. But I feel just having it scroll to the Process is better.

**Comment by LizCottrell** [comment]
@Wholloran - this is now QA ready on https://openforge-dev.firebaseapp.com/

Instead of doing any fixes on the button, I styled out the services section to be visible and responsive down to the smallest mobile viewport.  We don't have mobile designs for this yet, so horizontal scrolling is used to deal with the mobile navigation on the tabs (start up, enterprise, etc).

**Comment by Wholloran** [comment]
button now operates correctly closing the ticket
